parameters:
  relative_angle_threshold: 0.1
  rot_speed_1_threshold: 0.04
  relative_speed_angle_1_threshold: 0.04
  rot_speed_2_threshold: 0.07
  last_relative_angle_threshold: 0.01
  last_speed_threshold: 0.01

rocket:
  # normal distribiution
  # [x, y, angle_rad]
  loc: [-0.5, -0.7, 0]
  scale: [0.1, 0.1, 1.047]

planets:
  # [x, y, mass]
  - [0.5, 0.5, 1]
  - [0.75, -0.75, 0.5]
  - [-0.25, 0.75, 0.2]

environment:
  fps: 30
  scale: 2.5
  bound: 2.75  # 1.1 * scale
  viewport_w: 1200
  viewport_h: 800
  gravity_const: 0.001
  planet_dens: 10
  eps: 1e-6
  pulse_power: 2e-4
  rotation_power: 5e-8
