parameters:
  # all angles normalized from [-180, 180] to [-1, 1]
  relative_angle_threshold: 0.1
  target_rot_speed_threshold: 0.04
  danger_angle_threshold: 0.04
  emergency_rot_speed_threshold: 0.07
  target_relative_angle: 0.01
  danger_pull_angle_threshold: 0.7
  target_speed: 0.01

rocket:
  # normal distribiution
  # [x, y, angle_rad]
  loc: [-0.5, -0.7, 0]
  scale: [0.1, 0.1, 1.047]

planets:
  # [x, y, mass]
  - [0.5, 0.5, 1]
  - [0.75, -0.75, 0.5]
  - [-0.25, 0.75, 0.4]
  # - [-0.7, 0.55, 0.7]
  # - [0.7, 0, 0.4]

# seed: 779075522
# seed: 946061787  # orbiting
# seed: 679239139
# seed: 997813027

environment:
  fps: 30
  scale: 2.5
  bound: 2.75  # 1.1 * scale
  viewport_w: 1200
  viewport_h: 800
  gravity_const: 0.001
  planet_dens: 10
  eps: 1e-6
  pulse_power: 2e-4
  rotation_power: 5e-8
